import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — Tech Zi Wei",
};

export default function DisclaimerPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1>Disclaimer</h1>
      <p className="text-slate-500 text-sm">Last updated: May 22, 2026</p>

      <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 not-prose mb-8">
        <p className="font-semibold text-amber-800 mb-1">Important Notice</p>
        <p className="text-amber-700 text-sm leading-relaxed">
          Tech Zi Wei is provided <strong>for entertainment and self-reflection purposes only</strong>.
          It is <strong>not</strong> a substitute for professional medical, legal, financial,
          or psychological advice.
        </p>
      </div>

      <h2>1. Nature of the Service</h2>
      <p>
        Tech Zi Wei translates traditional Zi Wei Dou Shu (紫微斗數) astrological archetypes into
        contemporary psychological language. The reports, readings, and interpretations generated
        by this platform are:
      </p>
      <ul>
        <li>Based on a centuries-old symbolic system, not empirical science</li>
        <li>Generated by artificial intelligence trained on psychological and astrological frameworks</li>
        <li>Intended as prompts for personal reflection, not factual statements about your life</li>
        <li>Neither predictions nor prescriptions</li>
      </ul>

      <h2>2. Not a Substitute for Professional Advice</h2>
      <p>
        Nothing on this platform constitutes professional advice of any kind. Specifically:
      </p>
      <ul>
        <li>
          <strong>Medical / Mental Health:</strong> The reports generated are not a diagnosis,
          treatment, or clinical assessment. If you are experiencing mental health concerns, please
          consult a licensed mental health professional, psychiatrist, or physician.
        </li>
        <li>
          <strong>Psychological:</strong> Readings are not a substitute for therapy, counselling,
          or any licensed psychological service. Descriptions of personality, attachment style, or
          behavioural patterns are symbolic and speculative.
        </li>
        <li>
          <strong>Legal:</strong> No content on this platform constitutes legal advice. Do not make
          legal decisions based on astrological or AI-generated readings.
        </li>
        <li>
          <strong>Financial:</strong> Career and financial insights in our reports are exploratory
          reflections, not investment advice, financial planning, or endorsements of any financial
          action.
        </li>
        <li>
          <strong>Relationship / Life Decisions:</strong> Do not make significant life decisions —
          including decisions about relationships, career changes, or relocation — based solely on
          the readings provided by this platform.
        </li>
      </ul>

      <h2>3. Accuracy</h2>
      <p>
        We strive for accurate Zi Wei Dou Shu chart calculations according to traditional methods.
        However, chart results may vary depending on birth time precision, timezone interpretation,
        and differences between classical calculation schools. We make no warranty that calculations
        are free from error.
      </p>
      <p>
        AI-generated readings are probabilistic and may contain inaccuracies, inconsistencies, or
        content that does not reflect your lived experience. They should be treated as one
        perspective among many, not as objective truth.
      </p>

      <h2>4. Cultural Sensitivity</h2>
      <p>
        Zi Wei Dou Shu is a living cultural tradition originating in East Asia. We present this
        system with respect and with the explicit intention of making it accessible to a broader
        audience. The psychological framing used in our reports is our interpretation and does
        not represent the authoritative view of any traditional practitioner or cultural institution.
      </p>

      <h2>5. Crisis Resources</h2>
      <p>
        If you are in crisis or need immediate mental health support, please reach out to a
        professional service:
      </p>
      <ul>
        <li><strong>USA:</strong> 988 Suicide & Crisis Lifeline — call or text <strong>988</strong></li>
        <li><strong>Canada:</strong> Crisis Services Canada — <strong>1-833-456-4566</strong></li>
        <li><strong>UK:</strong> Samaritans — <strong>116 123</strong></li>
        <li><strong>International:</strong>{" "}
          <a href="https://www.findahelpline.com" target="_blank" rel="noopener noreferrer">
            findahelpline.com
          </a>
        </li>
      </ul>

      <h2>6. Limitation of Liability</h2>
      <p>
        Tech Zi Wei and its operators disclaim all liability for any decisions made, actions taken,
        or harm arising from reliance on the content provided by this platform. Use of this service
        is at your own discretion and risk.
      </p>

      <h2>7. Contact</h2>
      <p>
        Questions about this Disclaimer?{" "}
        <a href="mailto:legal@techziwei.com">legal@techziwei.com</a>
      </p>
    </article>
  );
}
