import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Tech Zi Wei",
};

export default function PrivacyPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1>Privacy Policy</h1>
      <p className="text-slate-500 text-sm">Last updated: May 22, 2026</p>

      <p>
        Tech Zi Wei (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the Tech Zi Wei platform at
        techziwei.com. This Privacy Policy explains what personal information we collect, how we use
        it, and the choices you have.
      </p>

      <h2>1. Information We Collect</h2>
      <h3>Account information</h3>
      <p>
        When you register, we collect your email address and a bcrypt-hashed password. We never
        store your plaintext password.
      </p>
      <h3>Birth data</h3>
      <p>
        To calculate a Zi Wei Dou Shu chart we collect your date of birth, time of birth, and the
        UTC timezone offset you select. We do not collect your birthplace beyond the timezone offset
        you provide.
      </p>
      <h3>Payment information</h3>
      <p>
        Payments are processed by <strong>Stripe, Inc.</strong> We never see or store your full card
        number, CVV, or billing address. We receive a Stripe Customer ID and payment confirmation
        from Stripe after a successful transaction. Stripe&apos;s privacy practices are governed by
        the <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">Stripe Privacy Policy</a>.
      </p>
      <h3>Usage data</h3>
      <p>
        We log standard server access logs (IP address, request path, timestamp, response code) for
        security and debugging. These logs are retained for 30 days.
      </p>

      <h2>2. How We Use Your Information</h2>
      <ul>
        <li>To calculate and display your Zi Wei Dou Shu chart</li>
        <li>To generate AI-powered psychological readings via the Anthropic API</li>
        <li>To process your payment and manage your subscription tier</li>
        <li>To authenticate you and secure your account</li>
        <li>To send transactional emails (receipt, password reset) — no marketing emails without
          your explicit consent</li>
        <li>To detect and prevent abuse, fraud, and security incidents</li>
      </ul>

      <h2>3. Third-Party Services</h2>
      <h3>Anthropic</h3>
      <p>
        AI readings are generated by sending a serialised version of your chart data (birth year,
        palace positions, and star placements — no name, email, or payment details) to the
        <strong> Anthropic API</strong>. Anthropic&apos;s data handling is governed by their{" "}
        <a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </a>. We use Anthropic&apos;s prompt-caching feature; cached content is never shared across
        users.
      </p>
      <h3>Stripe</h3>
      <p>
        Stripe processes all payments. By completing a purchase you also agree to
        Stripe&apos;s <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">
          Privacy Policy
        </a> and{" "}
        <a href="https://stripe.com/legal/ssa" target="_blank" rel="noopener noreferrer">
          Terms of Service
        </a>.
      </p>

      <h2>4. Data Retention</h2>
      <p>
        We retain your account and chart data for as long as your account is active. You may request
        deletion at any time (see section 5). Server logs are retained for 30 days. Stripe retains
        payment records as required by applicable law.
      </p>

      <h2>5. Your Rights</h2>
      <p>Depending on your jurisdiction you may have the right to:</p>
      <ul>
        <li><strong>Access</strong> — request a copy of your personal data</li>
        <li><strong>Correction</strong> — ask us to correct inaccurate data</li>
        <li><strong>Deletion</strong> — request that we delete your account and associated data</li>
        <li><strong>Portability</strong> — receive your chart data in a machine-readable format</li>
        <li><strong>Opt-out</strong> — opt out of any future marketing communications</li>
      </ul>
      <p>
        To exercise any of these rights, email us at{" "}
        <a href="mailto:privacy@techziwei.com">privacy@techziwei.com</a>. We will respond within
        30 days.
      </p>

      <h2>6. Cookies</h2>
      <p>
        We do not use tracking cookies. Authentication state is maintained via a JWT stored in
        your browser&apos;s <code>localStorage</code>. No third-party advertising cookies are set.
      </p>

      <h2>7. Children&apos;s Privacy</h2>
      <p>
        Our service is not directed at children under 13. We do not knowingly collect personal
        information from children under 13. If you believe a child has provided us with personal
        information, please contact us and we will delete it promptly.
      </p>

      <h2>8. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will post the revised version with
        an updated &quot;Last updated&quot; date. Continued use of the service after changes
        constitutes acceptance.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions about this Privacy Policy?{" "}
        <a href="mailto:privacy@techziwei.com">privacy@techziwei.com</a>
      </p>
    </article>
  );
}
